version: '3.8'

services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - monitoring

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3003:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_SMTP_ENABLED=true
      - GF_SMTP_HOST=smtp.gmail.com:587
      - GF_SMTP_USER=angalikiranreddy1995@gmail.com
      - GF_SMTP_PASSWORD=svqqaagxtsncqsqx  # Ensure no spaces in the password
      - GF_SMTP_FROM_ADDRESS=angalikiranreddy1995@gmail.com
      - GF_SMTP_FROM_NAME=Grafana
    volumes:
      - ./provisioning:/etc/grafana/provisioning  # Corrected path
    networks:
      - monitoring
    depends_on:
      - prometheus

  kafka-exporter:
    image: danielqsj/kafka-exporter:latest
    container_name: kafka-exporter
    environment:
      - KAFKA_SERVER=your-kafka-server:9092
    ports:
      - "9308:9308"
    networks:
      - monitoring
    depends_on:
      - prometheus

networks:
  monitoring: